spring:
  datasource:
    url: ${MALL_DB_URL:jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false}
    username: ${MALL_DB_USERNAME}
    password: ${MALL_DB_PASSWORD}
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: ${DRUID_USERNAME}
        login-password: ${DRUID_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      database: ${REDIS_DATABASE:0}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 300ms

jwt:
  secret: ${MALL_ADMIN_JWT_SECRET}

minio:
  endpoint: ${MINIO_ENDPOINT}
  bucketName: ${MINIO_BUCKET:mall}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info

logstash:
  host: ${LOGSTASH_HOST:logstash}
