spring:
  datasource:
    url: ${MALL_DB_URL:jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false}
    username: ${MALL_DB_USERNAME}
    password: ${MALL_DB_PASSWORD}
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: ${DRUID_USERNAME}
        login-password: ${DRUID_PASSWORD}
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://es:9200}

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info

logstash:
  host: ${LOGSTASH_HOST:logstash}
